version: "3.5"

services:
  postgres:
    image: postgres:latest
    volumes:
      - nepali-calendar-db:/var/lib/postgresql/data
    ports:
      - "5466:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  calendar: 
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports: 
      - "8888:80"
    volumes:
      - /calendar/node_modules
      - ./src/:/calendar/src/
      - ./config/:/calendar/config/
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
volumes:
  nepali-calendar-db:
